# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
imports:
    - { resource: 'parameters.yml' }

parameters:
    secret: '%env(APP_SECRET)%'
    admin.auth: false
    admin.users: [ ]
    log.handler: 'file_log'
    log.level: 'error'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\DTO\Configuration:
        lazy: true
        factory: [ '@App\Service\RepositoryManager', 'getConfig' ]

    App\Persister\FilePersister:
        arguments:
            $filename: "%satis_filename%"
            $logPath: "%satis_log_path%"

    App\Persister\JsonPersister:
        class: App\Persister\JsonPersister
        public: false
        arguments:
            - '@App\Persister\FilePersister'
            - "@serializer"
            - 'App\DTO\Configuration'

    App\Persister\ConfigurationNormalizer:
        tags:
            - { name: serializer.normalizer, priority: 1000 }

    App\Process\EnvironmentProvider:
        arguments:
            $composerHome: "%composer.home%"


    App\Process\ProcessFactory:
        arguments:
            $rootPath: "%kernel.project_dir%"
            $envProvider: '@App\Process\EnvironmentProvider'

    App\Service\SatisManager:
        public: true
        arguments:
            $satisFilename: "%satis_filename%"

    App\Validator\EnvValidator:
        public: true
        arguments:
            $root: "%kernel.project_dir%"
            $satisFilename: "%satis_filename%"
            $composerHome: "%composer.home%"
